#!/usr/bin/env python3
"""Render dataset_full.json into the ranked markdown deliverable."""
import json, os, datetime as dt

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.abspath(os.path.join(HERE, "..", "08_fda_ipl_device_dataset.md"))


def brand_short(b):
    b = b.replace(", Ltd.", "").replace(" Co.", "").replace(",", "")
    for junk in ["Shenzhen ", "Dongguan ", "Foshan ", "Beijing ", "Wuhan ",
                 "Intelligent Technology", "Science and Technology", "Technology",
                 "Smart Electronics", "Electronic", "Electric Appliance",
                 "Consumer Lifestyle B.V.", "Healthcare", "Industrial"]:
        b = b.replace(junk, "")
    return " ".join(b.split())[:26] or "—"


def f(x):
    return "—" if x in (None, "", "None") else (f"{x:g}" if isinstance(x, (int, float)) else str(x))


def link(k):
    return f"[{k}](https://www.accessdata.fda.gov/cdrh_docs/pdf{int(k[1:3])}/{k}.pdf)"


def row(r, rank=None):
    mp = "🔴 yes" if r["multi_pulse"] == "YES" else (
        "no" if r["multi_pulse"] == "no" else "?")
    conf = "✅" if r["confidence"] == "verified" else "~"
    cells = [
        f(r["fluence_jcm2"]), conf, brand_short(r["brand"]),
        f(r["spot_cm2"]), f(r["energy_j"]), f(r["wavelength_nm"]) or "—",
        mp, r["decision_date"][:7], link(r["k_number"]),
    ]
    if rank is not None:
        cells = [str(rank)] + cells
    return "| " + " | ".join(cells) + " |"


def table(rows, ranked=True):
    head = (["#"] if ranked else []) + [
        "J/cm²", "✓", "Brand", "Spot cm²", "J/flash", "Wavelength nm",
        "Multi-pulse", "Cleared", "FDA 510(k) PDF"]
    sep = ["---"] * len(head)
    lines = ["| " + " | ".join(head) + " |", "| " + " | ".join(sep) + " |"]
    for i, r in enumerate(rows, 1):
        lines.append(row(r, i if ranked else None))
    return "\n".join(lines)


def main():
    d = json.load(open(os.path.join(DATA, "dataset_full.json")))
    today = dt.date.today().isoformat()

    def has_text(r): return r["pdf_status"] in ("ok", "ok_ocr")
    oht = [r for r in d if r["product_code"] == "OHT"]
    ipl_home = [r for r in oht if r["light_source"] == "ipl" and has_text(r)]
    diode_home = [r for r in oht if r["light_source"] == "diode" and has_text(r)]
    unknown_home = [r for r in oht if r["light_source"] == "unknown" or not has_text(r)]
    pro = [r for r in d if r["product_code"] in ("GEX", "ONF")]

    def fl(r): return r["fluence_jcm2"] if isinstance(r["fluence_jcm2"], (int, float)) else -1
    ipl_home.sort(key=fl, reverse=True)
    diode_home.sort(key=fl, reverse=True)
    unknown_home.sort(key=lambda r: r["decision_date"], reverse=True)
    pro.sort(key=lambda r: r["decision_date"], reverse=True)

    verified = [r for r in ipl_home if r["confidence"] == "verified"]
    nver = len(verified)

    parts = []
    parts.append(f"""# FDA 510(k) IPL Device Dataset — Ranked by Fluence (J/cm²)

*Auto-generated by the `fda_data_pipeline` from openFDA + the 510(k) summary PDFs.
Last built {today}.*

This ranks **home / over-the-counter (OTC) IPL hair-removal devices** (FDA product
code **OHT**) by their cleared **maximum energy density (J/cm²)** — the spec that
actually drives treatment intensity. Every row links to the FDA 510(k) summary PDF.

## How to read this — IMPORTANT
- **J/cm² = the cleared MAX energy density of the *subject* device** (not a predicate
  or reference device in the same filing). The ✓ column shows confidence:
  **✅ = hand-read from the filing's spec table** ({nver} devices);
  **~ = auto-extracted** (regex best-guess, may include extraction error — verify via the PDF).
- **Multi-pulse 🔴**: the filing describes double/triple/multi-pulse firing, so a big
  advertised "joules" number is a **summed pulse train**, not single-pulse output.
  For these, the true per-pulse fluence is a fraction of the J/flash figure. This is
  the joule-inflation pattern you flagged — the flag tells you exactly where it applies.
- **J/flash** = max output energy (J) where the filing stated it; for multi-pulse
  devices this is the summed train. Many filings report only J/cm², shown as "—".
- **Spot cm²** = treatment window size. **Wavelength nm** = filter range
  (510–530nm low cutoff is better for vascular/pigment; 560nm+ is hair-only).

---

## 1. Home IPL devices — ranked by cleared J/cm²  ({len(ipl_home)} devices)

> True Xenon-flashlamp IPL only. The {nver} ✅ rows are hand-verified; the rest are
> auto-extracted and flagged. The top of this ranking is fully hand-verified.

{table(ipl_home)}
""")

    parts.append(f"""
---

## 2. ⚠️ NOT IPL — diode-laser / LED hair-removal devices under OHT  ({len(diode_home)} devices)

These were cleared under the same OHT product code but use an **810nm diode laser or
LED**, not Intense Pulsed Light. Their high J/cm² (single-wavelength) is **not
comparable** to IPL fluence — listed separately so they don't distort the IPL ranking.

{table(diode_home)}
""")

    if unknown_home:
        parts.append(f"""
---

## 3. Other OHT hair-removal clearances — emitter not auto-classified / no PDF  ({len(unknown_home)} devices)

Auto-extracted only; light source not confidently classified or summary PDF
unavailable. Open the filing to confirm. Sorted newest first.

{table(unknown_home, ranked=False)}
""")

    parts.append(f"""
---

## 4. Professional / clinic IPL & laser (product codes GEX, ONF)  ({len(pro)} devices)

Prescription/clinic systems — different regulatory basis and far higher fluence than
home devices; included for completeness, not for home-purchase comparison. Auto-extracted.
Sorted newest first.

{table(pro, ranked=False)}
""")

    parts.append(f"""
---

## Methodology & provenance

- **Source:** openFDA 510(k) API (metadata) + each clearance's FDA 510(k) summary PDF
  (specs). Pulled and parsed by `fda_data_pipeline/` (see its `STRATEGY.md`).
- **Coverage:** full census of OHT (home IPL) — {len([r for r in oht])} clearances —
  plus GEX/ONF IPL devices caught by a device-name sweep. 160/162 OHT filings have
  machine-readable text (98.8%); 2 unavailable (1 Adobe-portfolio PDF, 1 not yet posted).
- **Fluence isolation:** the comparison tables interleave subject + predicate +
  reference devices, and no regex reliably separates them (validated against known
  values). So fluence was **hand-read from the spec table for the {nver} decision-
  relevant devices** (the verified ✅ set, which covers the top of the ranking); the
  remainder are auto-extracted and flagged ~ for you to verify via the linked PDF.
- **Known auto caveats:** auto J/cm² may grab a reference device's value (e.g. several
  Ulike filings list a "7–10 J/cm²" reference; the Ulike *subject* device is 6.4–7.3).
  Where it mattered for ranking, those were hand-corrected.

*To regenerate: `python3 build_dataset.py && python3 make_markdown.py`. To verify more
devices, add them to `verified_specs.json` and rebuild.*
""")

    with open(OUT, "w") as fh:
        fh.write("\n".join(parts))
    print(f"Wrote {OUT}")
    print(f"  IPL home: {len(ipl_home)} ({nver} verified)  |  diode: {len(diode_home)}"
          f"  |  other OHT: {len(unknown_home)}  |  pro GEX/ONF: {len(pro)}")


if __name__ == "__main__":
    main()
