#!/usr/bin/env python3
"""Embed routed Markdown sources in a browser-side fetch shim for offline viewing."""

from __future__ import annotations

import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
ROUTER = ROOT / "site-router.js"
OUTPUT = ROOT / "site-documents.js"


def routed_markdown() -> dict[str, str]:
    router_source = ROUTER.read_text(encoding="utf-8")
    match = re.search(r"\bconst ROUTES=(\{.*?\});", router_source, re.DOTALL)
    if not match:
        raise RuntimeError("Could not read the generated ROUTES map from site-router.js")

    routes = json.loads(match.group(1))
    # Keep manually appended runtime routes available to the offline bundle as
    # well. The repository's generated route map is normally a single JSON
    # object, but some older checkouts append a route assignment after it.
    for relative_path, route_id, index in re.findall(
        r'ROUTES\["([^"]+)"\]=\{"id":"([^"]+)","index":"([^"]+)"\};',
        router_source,
    ):
        routes[relative_path] = {"id": route_id, "index": index}
    documents: dict[str, str] = {}
    missing: list[str] = []
    for relative_path in sorted(routes):
        if not relative_path.lower().endswith(".md"):
            continue
        source_file = ROOT / relative_path
        if not source_file.is_file():
            missing.append(relative_path)
            continue
        documents[relative_path] = source_file.read_text(encoding="utf-8")

    if missing:
        raise RuntimeError("Routed Markdown files are missing: " + ", ".join(missing))
    return documents


def render_asset(documents: dict[str, str]) -> str:
    payload = json.dumps(documents, ensure_ascii=True, separators=(",", ":"))
    return f'''/* Generated by tools/build_embedded_documents.py. Do not edit by hand. */
(function(){{
  "use strict";
  const SOURCES={payload};
  window.SiteEmbeddedDocuments=Object.freeze(SOURCES);
  if(window.__siteEmbeddedFetchInstalled)return;
  window.__siteEmbeddedFetchInstalled=true;
  const nativeFetch=window.fetch.bind(window);
  const script=document.currentScript;
  const root=new URL("./",script.src);
  function keyFor(url){{
    const rootPath=decodeURIComponent(root.pathname).replace(/\\/$/,"")+"/";
    const path=decodeURIComponent(url.pathname);
    return path.startsWith(rootPath)?path.slice(rootPath.length):null;
  }}
  window.fetch=function(resource,options){{
    const method=(options&&options.method)||(typeof Request!=="undefined"&&resource instanceof Request?resource.method:"GET");
    if(String(method).toUpperCase()==="GET"){{
      try{{
        const raw=typeof resource==="string"?resource:(typeof URL!=="undefined"&&resource instanceof URL?resource.href:resource.url);
        const url=new URL(raw,document.baseURI);
        if(url.pathname.toLowerCase().endsWith(".md")){{
          const key=keyFor(url);
          if(key!==null&&Object.prototype.hasOwnProperty.call(SOURCES,key)){{
            return Promise.resolve(new Response(SOURCES[key],{{status:200,headers:{{"Content-Type":"text/markdown; charset=utf-8","X-Research-Source":"embedded"}}}}));
          }}
        }}
      }}catch(_error){{}}
    }}
    return nativeFetch(resource,options);
  }};
}})();
'''


def main() -> int:
    try:
        documents = routed_markdown()
        OUTPUT.write_text(render_asset(documents), encoding="utf-8")
    except Exception as error:
        print(f"ERROR {error}", file=sys.stderr)
        return 1

    size_kib = OUTPUT.stat().st_size / 1024
    print(f"WROTE {OUTPUT} ({len(documents)} documents, {size_kib:.1f} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
