const fs=require('fs'),path=require('path'),marked=require('./marked.umd.js');
const files=['01_mechanisms.md','02_evidence_audit.md','03_device_comparison.md','04_ingredient_fit.md','05_prices_and_value.md','README.md','06_source_library.md','source_docs/README.md'];
const titles=['Mechanisms','Evidence audit','Device comparison','Your ingredients','eBay & value','Start here','Source library','Preservation manifest'];
const dir=__dirname;
const docs=files.map((file,i)=>({id:'doc'+(i+1),file,title:titles[i],md:fs.readFileSync(path.join(dir,file),'utf8')}));
let sections=docs.map(d=>`<section class="doc" id="${d.id}"><a class="openmd" hidden aria-hidden="true" tabindex="-1" href="${d.file}"></a>${marked.parse(fs.readFileSync(path.join(dir,d.file),'utf8')).replace(/href="([^"]+)"/g,(m,u)=>d.file.startsWith('source_docs/')&&!/^(https?:|#)/.test(u)?'href="'+path.posix.normalize('source_docs/'+u)+'"':m)}</section>`).join('\n');
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Skincare Penetration • Device Research</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E⚡%3C/text%3E%3C/svg%3E"><script src="../site-router.js" defer></script><script src="../site-documents.js" defer></script><style>
.openmd,[data-raw-download],[data-mode="m"],.raw{display:none!important}:root{color-scheme:light;--ink:#193438;--accent:#117c81;--line:#d9e7e5}*{box-sizing:border-box}body{margin:0;background:#f3f8f7;color:var(--ink);font:16px/1.65 system-ui,sans-serif}a{color:#086b85;text-underline-offset:3px}header{padding:34px max(24px,calc((100vw - 1240px)/2));background:#153e43;color:white}header a{color:#b9eeeb}header h1{font-size:clamp(28px,4vw,43px);line-height:1.15;margin:18px 0 12px}header p{max-width:850px;color:#d9e9e8}.wrap{max-width:1240px;margin:auto;padding:26px 22px;display:grid;grid-template-columns:210px minmax(0,1fr);gap:28px}nav{position:sticky;top:20px;align-self:start;display:flex;flex-direction:column;gap:5px}nav a{padding:8px 12px;border-radius:8px;text-decoration:none}nav a.active{background:#d9ece9;font-weight:700}main{min-width:0}.panel,.doc{background:white;border:1px solid var(--line);border-radius:15px;padding:25px;margin-bottom:24px}.doc{display:none;overflow-wrap:anywhere}.doc.active{display:block}.doc h1{font-size:29px;line-height:1.25;margin-top:0}.doc h2{font-size:23px;margin-top:30px}.doc p{max-width:80ch}.doc table{border-collapse:collapse;font-size:14px;min-width:650px;width:100%}.table-scroll{overflow:auto;margin:20px 0}th,td{text-align:left;vertical-align:top;padding:12px;border-bottom:1px solid var(--line)}th{background:#eff7f5}td:first-child{min-width:135px}label{display:block;font-weight:650}select,input{font:inherit;width:100%;padding:10px;border:1px solid #a8c5c2;border-radius:8px;background:white;color:var(--ink)}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.note{padding:16px;background:#edf6f3;border-left:4px solid var(--accent);margin:16px 0}.small{font-size:13px;color:#536e70}.result{font-size:25px;font-weight:700;margin:16px 0 0}.badge{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#78d9d1}.panel h2{margin:0 0 14px;font-size:21px}.doc ul,.doc ol{padding-left:25px}footer{padding:20px;font-size:13px;text-align:center}.all-link{font-weight:700}@media(max-width:760px){.wrap{display:block;padding:15px}nav{position:static;flex-direction:row;overflow:auto;padding-bottom:12px;gap:4px}nav a{white-space:nowrap;font-size:13px;padding:7px 10px}.grid{grid-template-columns:1fr}.panel,.doc{padding:18px;border-radius:12px}.doc h1{font-size:25px}header{padding:22px}.small{font-size:13px}}@media print{header,nav,.panel,footer{display:none}.wrap{display:block}.doc{display:block!important;border:0}.table-scroll{overflow:visible}.doc table{min-width:0}}
</style></head><body><header><a href="../index.html">← Research archive</a><div class="badge">Topic 23 · Updated October 1, 2026</div><h1>Skincare penetration: is a device worth it?</h1><p>Electroporation, iontophoresis and related technologies. Compare Panasonic, YA-MAN and Medicube against your actual ingredients and budget.</p></header><div class="wrap"><nav aria-label="Research guides">${docs.map(d=>`<a href="#${d.id}">${d.title}</a>`).join('')}<a href="source_docs/research_resource_log_2026-10-01.txt">Research log</a><a href="data/ebay_snapshot_2026-10-01.csv">Price dataset</a></nav><main>
<div class="panel"><h2>Match the purchase to the ingredient</h2><label for="ingredient">Ingredient in your routine</label><select id="ingredient"><option value="routine">Your full five-active routine</option value="c">Vitamin C</option><option value="n">Niacinamide</option><option value="a">Azelaic acid</option><option value="t">Thiamidol</option><option value="r">Tazarotene / prescription retinoids</option><option value="h">HA / hydrophilic peptides</option></select><div id="fit" class="note" role="status"></div><p class="small">Evidence-linked decision aid, not an efficacy model. <a href="#doc4">Read the formula-specific limits →</a></p></div>
<div class="panel"><h2>Cost per hypothetical use</h2><div class="grid"><div><label for="price">Delivered price, USD</label><input id="price" type="number" min="0" max="10000" step="0.01" value="110"></div><div><label for="uses">Uses per week</label><input id="uses" type="number" min="0.1" max="100" step="0.1" value="2"></div><div><label for="weeks">Weeks of ownership</label><input id="weeks" type="number" min="1" max="1000" step="1" value="52"></div></div><div id="cost" class="result" role="status"></div><p class="small">Cost = price ÷ (uses/week × weeks). Default 2 × 52 is a spending scenario, not recommended frequency. Excludes taxes, consumables, failures and resale; predicts no clinical benefit. <a href="#doc5">Compare dated offers →</a></p></div>
${sections}</main></div><footer>Manufacturers’ uptake ratios are ingredient- and assay-specific. Prices are dated asking offers. All research guides render locally and on a served site.</footer><script>
const DOCS=${JSON.stringify(docs)};
const fitText={routine:'Best value: keep your ordinary topical routine. No located matched-formula clinical trial establishes an incremental benefit for these five actives. Optional low-cost experiments are easiest to justify; avoid boosting the prescription/irritating actives.',c:'Most plausible optional fit: a compatible vitamin C ion protocol. Formula and vitamin form matter. Small clinical studies support combined treatments, but do not isolate the added device benefit. Acidic L-ascorbic acid may increase stinging.',n:'Low-priority experiment: ordinary topical niacinamide already has controlled human evidence. YA-MAN uptake testing is relevant, but does not establish better clinical results or justify a costly upgrade.',a:'Poor fit for routine boosting: no established incremental consumer-device benefit; burning/stinging is already a formulation concern. Prefer ordinary application.',t:'Poor value for boosting: vehicle-controlled topical Thiamidol evidence exists, but no located finished-product device trial. Follow its product instructions.',r:'Do not use tazarotene as the booster serum. Extra prescription delivery has unestablished benefit and may increase irritation; discuss any deliberate enhancement with the prescriber.',h:'Closest fit to the large-molecule marketing tests: Panasonic BOOST studies measure HA/peptide delivery into the outer barrier. This still does not establish deeper wrinkle benefit.'};
function show(){let id=location.hash.slice(1)||'doc6';if(!DOCS.some(d=>d.id===id))id='doc6';document.querySelectorAll('.doc').forEach(d=>d.classList.toggle('active',d.id===id));document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));}
function fit(){document.getElementById('fit').textContent=fitText[document.getElementById('ingredient').value]}
function cost(){let p=Number(document.getElementById('price').value),u=Number(document.getElementById('uses').value),w=Number(document.getElementById('weeks').value);document.getElementById('cost').textContent=Number.isFinite(p+u+w)&&p>=0&&u>0&&w>0?'$'+(p/(u*w)).toFixed(2)+' per use · '+(u*w).toLocaleString()+' hypothetical uses':'Enter a nonnegative price and positive usage and duration.'}
document.querySelectorAll('.doc table').forEach(t=>{const div=document.createElement('div');div.className='table-scroll';div.tabIndex=0;div.setAttribute('aria-label','Scrollable comparison table');t.before(div);div.append(t)});document.getElementById('ingredient').addEventListener('change',fit);['price','uses','weeks'].forEach(id=>document.getElementById(id).addEventListener('input',cost));addEventListener('hashchange',show);show();fit();cost();
</script></body></html>`;
fs.writeFileSync(path.join(dir,'index.html'),page);
